function idx=tc_lineinmatind(img,target1,target2,linewidth)
%% idx=tc_lineinmatind(img,target1,target2,linewidth)
% Output: matrix indices of cells on a line of width 'linewidth' between
% 'target1' and 'target2'
% example: imagesc(tc_lineinmatind(rand(768,1024),[300,300],[600,600],10))

poly_=[...
    target1-[floor(linewidth/2), - floor(linewidth/2)];...
    target1+[ceil(linewidth/2),  - ceil(linewidth/2)];...
    target2+[ceil(linewidth/2),  - ceil(linewidth/2)];...
    target2-[floor(linewidth/2), - floor(linewidth/2)]...
    ];

[xq,yq]=meshgrid(1:size(img,1),1:size(img,2));
idx=inpolygon(xq,yq,poly_(:,1),poly_(:,2));